version: "3"

services:
  mysql:
    restart: always
    image: mysql:5.7
    ports:
      - "3306:3306"

  app:
    restart: always
    build: ./apm
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      DEBUG: "true"
